name: release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'testpacorgrole' # do not run this elsewhere
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - run: git fetch --prune --unshallow
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
      with:
        go-version: 1.22.x
        cache: true
    - uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --timeout=60m --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
